### ISSUE TITLE
Add timeline disclaimer to nonprofit application portal

### ISSUE THREAD

**Issue by marissagardner** [GTBitsOfGood/nonprofit-portal#66]
Add a disclaimer underneath "As a partner, Bits of Good will help you build software that turns your need into real product. Please fill out the following form so that we can best understand your mission and need!" on the Nonprofit Application Portal (found at [https://apply.bitsofgood.org/]) stating:
"If you apply on or after September 7, 2021, you can expect to hear back from us within a week to set up a follow-up meeting and you will be considered for the Spring 2022 project cycle.
If you apply between November 17, 2021, and January 24, 2022, you can expect to hear back from us by January 25, 2022, to set up a follow-up meeting and you will be considered for the Fall 2022 project cycle.
If you apply on or after January 25, 2022, you can expect to hear back from us within a week to set up a follow-up meeting and you will be considered for the Fall 2022 project cycle"

Acceptance Criteria: This change will be considered done once the disclaimer is visible to nonprofits applying on the nonprofit portal.

**Comment by Fattimo** [comment]
@marissagardner 
![image](https://user-images.githubusercontent.com/57023314/132596024-c4dd2350-8aba-4d7f-97b0-62b31c6f03a6.png)
this is the result if we explicitly list all of the content below

Here is the change that's currently on my branch, let me know if there is something that is more desirable or if we should find a designer to proof any of this:

![image](https://user-images.githubusercontent.com/57023314/132597483-894a1995-8be7-469a-bb28-d7608bc54a4e.png)

Take a look over the content as well, I may have missed things while copying everything. If I could get a deadline for the last time range as well that would make everything symmetrical.

**Comment by Fattimo** [comment]
probably can extend the width of the dates column

**Comment by Fattimo** [comment]
@stephanie-he @lilliniunni idk if you have any qualms or preferences or suggestions with these designs
